# Configuration for BSides Oslo 2020 website. This
# file contains most of the variables for the information on the website.

title: BSides Oslo 2022
date: May 25th, 2022

description: "BSides Oslo is an inclusive community driven information security event. BSides 2022 will be held on May 25th, 2022."

baseurl: ""

twitter_username: OsloBSides
youtube_channel: https://www.youtube.com/channel/UC6kTOacrQTu1ahmRCvXhhrA 
youtube_livestream: "#"

ticket_sale_url: https://www.deltager.no/event/Bsidesoslo2022

cfp:
  form: https://docs.google.com/forms/d/1uJlNye9siMFAV6OIANMIKEU8lKJOZSp6uuOW0d4rcuY
  deadline: "Feb 27th, 2022 23:59 CET"

emails:
  info: info@bsidesoslo.no
  sponsors: sponsors@bsidesoslo.no
  cfp: cfp@bsidesoslo.no
  returns: 2021@bsidesoslo.no

social:
- title: twitter
  url: https://twitter.com/OsloBSides
- title: youtube
  url: https://www.youtube.com/channel/UC6kTOacrQTu1ahmRCvXhhrA
- title: envelope
  url: mailto:info@bsidesoslo.no

# Build settings

exclude: 
- README.md
- LICENSE
- Dockerfile
- CNAME
- CODE_OF_CONDUCT.md
  

menu:
- title: Tickets
  url: https://www.deltager.no/event/Bsidesoslo2022
- title: Speakers
  url: "/#speakers"
- title: Sponsors
  url: "/#sponsors"
- title: About
  url: "/#about"
- title: Code of Conduct
  url: "/code-of-conduct"

site_features:
  cfp: false
  speakers: true


collections:
  talks:
    output: true
